#!/usr/bin/env python3
"""Profile a SwarmEvolve match under NVIDIA Nsight Systems.

Wraps ``nsys profile`` around a ``./swarmevolve`` invocation and emits:

1. A ``.nsys-rep`` archive (the raw Nsight report).
2. A set of CSV files generated by ``nsys stats`` containing per-kernel
   and per-memory-transfer aggregates (GPU-kernel execution time, CUDA
   memory-op time, and OpenACC runtime trace).
3. A small ``summary.json`` with the top-N kernel names, their total
   GPU time, and the overall wall-clock duration of the match.

The script is side-effect-free on hosts without ``nsys`` (e.g. macOS) —
it will fail with ``EXIT_NSYS_MISSING`` and a helpful message rather
than silently skip. M11 exit criterion: the generated CSVs are the
source of truth for ``docs/profiling/<date>.md``.

Typical invocation::

    python3 scripts/profile.py \\
        --binary ./swarmevolve \\
        --out data/profiles/run001 \\
        --seed 42 --max-ticks 1000

Exit codes
----------
0 : profile + stats succeeded, CSVs written.
2 : CLI usage error (argparse).
40: nsys executable not found on PATH.
41: binary (or its prerequisites) missing / not executable.
42: nsys profile or nsys stats returned non-zero.
"""

from __future__ import annotations

import argparse
import csv
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_NSYS_MISSING = 40
EXIT_BINARY_MISSING = 41
EXIT_NSYS_FAILED = 42

# Nsight Systems stat "reports" we care about. The names are the CLI
# identifiers used by `nsys stats --report <name>`; verified against
# nsys 2025.3.2.474.
STAT_REPORTS = (
    "cuda_gpu_kern_sum",  # per-kernel GPU time totals
    "cuda_gpu_mem_time_sum",  # per-memcpy-kind totals
    "openacc_sum",  # OpenACC runtime events (when -t=openacc)
)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run `nsys profile` around a SwarmEvolve match and emit CSVs.",
    )
    p.add_argument(
        "--binary", type=Path, required=True, help="Path to the swarmevolve binary (GPU build)"
    )
    p.add_argument("--out", type=Path, required=True, help="Output directory; created if missing")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--max-ticks", type=int, default=1000)
    p.add_argument(
        "--drones-a", type=int, default=None, help="Optional override (passed to --drones-a)"
    )
    p.add_argument(
        "--drones-b", type=int, default=None, help="Optional override (passed to --drones-b)"
    )
    p.add_argument(
        "--record", type=Path, default=None, help="Optional trace output path (passed to --record)"
    )
    p.add_argument(
        "--top", type=int, default=10, help="Include top-N kernels in summary.json (default 10)"
    )
    p.add_argument(
        "--trace", default="cuda,openacc,osrt,nvtx", help="Comma-separated -t list for nsys profile"
    )
    p.add_argument("--nsys", default="nsys", help="Path to nsys executable (default: look on PATH)")
    return p


def _fail(code: int, msg: str) -> int:
    print(f"profile.py: {msg}", file=sys.stderr)
    return code


def _run_nsys_profile(nsys: str, report_path: Path, trace: str, cmd: list[str]) -> int:
    """Run ``nsys profile -o <report_path> -t <trace> -- cmd...``."""
    full = [
        nsys,
        "profile",
        "-o",
        str(report_path.with_suffix("")),  # nsys appends .nsys-rep
        "-t",
        trace,
        "--force-overwrite=true",
        "--stats=false",  # we run `nsys stats` ourselves for controlled CSVs
        "--",
        *cmd,
    ]
    proc = subprocess.run(full, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
    return proc.returncode


def _run_nsys_stats(nsys: str, report_path: Path, out_dir: Path) -> dict[str, Path]:
    """Run ``nsys stats`` once per report name, writing CSV files."""
    written: dict[str, Path] = {}
    for name in STAT_REPORTS:
        out_csv = out_dir / f"{name}.csv"
        cmd = [
            nsys,
            "stats",
            "--report",
            name,
            "--format",
            "csv",
            "--output",
            str(out_csv.with_suffix("")),  # nsys appends _<report>.csv
            "--force-export=true",
            str(report_path),
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            # Some reports (e.g. openacc_sum) may legitimately produce no rows
            # if the trace domain wasn't enabled. We tolerate non-zero exit
            # only when the stderr indicates "No data found".
            lower = (proc.stdout + proc.stderr).lower()
            if "no data" in lower or "no events" in lower:
                print(f"profile.py: {name}: no data", file=sys.stderr)
                continue
            sys.stderr.write(proc.stdout)
            sys.stderr.write(proc.stderr)
            raise RuntimeError(f"nsys stats --report {name} failed")

        # nsys 2025 appends `_<report>.csv` to the --output stem.
        produced = list(out_dir.glob(f"{out_csv.stem}_{name}.csv"))
        # Fallback: maybe the file was written with the stem we asked for.
        if not produced and out_csv.exists():
            produced = [out_csv]
        if produced:
            written[name] = produced[0]
    return written


def _summarise(csv_paths: dict[str, Path], top: int, wallclock_sec: float) -> dict:
    summary: dict = {
        "wallclock_sec": wallclock_sec,
        "top_kernels": [],
        "memcpy_kinds": [],
    }
    kern_csv = csv_paths.get("cuda_gpu_kern_sum")
    if kern_csv and kern_csv.exists():
        rows = _parse_csv(kern_csv)
        # Rank by total time column; column names vary across nsys versions
        # ("Total Time (ns)" vs "Time (ns)"). Pick the first numeric column
        # whose header contains "Total Time".
        time_col = _find_column(rows, want_substr="total time")
        name_col = _find_column(rows, want_substr="name")
        if time_col and name_col:
            ranked = sorted(
                rows,
                key=lambda r: _to_float(r.get(time_col, 0)),
                reverse=True,
            )[:top]
            for r in ranked:
                summary["top_kernels"].append(
                    {
                        "name": r.get(name_col, "?"),
                        "total_ns": _to_float(r.get(time_col, 0)),
                        "instances": _to_int(r.get(_find_column(rows, "instances") or "", 0)),
                    }
                )

    mem_csv = csv_paths.get("cuda_gpu_mem_time_sum")
    if mem_csv and mem_csv.exists():
        rows = _parse_csv(mem_csv)
        time_col = _find_column(rows, "total time")
        kind_col = _find_column(rows, "operation") or _find_column(rows, "kind")
        if time_col and kind_col:
            for r in rows:
                summary["memcpy_kinds"].append(
                    {
                        "kind": r.get(kind_col, "?"),
                        "total_ns": _to_float(r.get(time_col, 0)),
                    }
                )
    return summary


def _parse_csv(path: Path) -> list[dict[str, str]]:
    with path.open() as f:
        reader = csv.DictReader(f)
        return list(reader)


def _find_column(rows: list[dict[str, str]], want_substr: str) -> str | None:
    if not rows:
        return None
    want_substr = want_substr.lower()
    for key in rows[0]:
        if key and want_substr in key.lower():
            return key
    return None


def _to_float(x: object) -> float:
    try:
        return float(str(x).replace(",", ""))
    except (ValueError, TypeError):
        return 0.0


def _to_int(x: object) -> int:
    try:
        return int(float(str(x).replace(",", "")))
    except (ValueError, TypeError):
        return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    nsys_path = shutil.which(args.nsys) or (args.nsys if Path(args.nsys).is_file() else None)
    if nsys_path is None:
        return _fail(
            EXIT_NSYS_MISSING,
            f"nsys not found on PATH (tried {args.nsys!r}). "
            "Install NVIDIA Nsight Systems or pass --nsys /path/to/nsys.",
        )

    if not args.binary.exists() or not args.binary.is_file():
        return _fail(EXIT_BINARY_MISSING, f"binary not found: {args.binary}")

    args.out.mkdir(parents=True, exist_ok=True)
    report_path = args.out / "profile.nsys-rep"

    sim_cmd: list[str] = [
        str(args.binary.resolve()),
        "--seed",
        str(args.seed),
        "--max-ticks",
        str(args.max_ticks),
    ]
    if args.drones_a is not None:
        sim_cmd += ["--drones-a", str(args.drones_a)]
    if args.drones_b is not None:
        sim_cmd += ["--drones-b", str(args.drones_b)]
    if args.record is not None:
        sim_cmd += ["--record", str(args.record)]

    t0 = time.perf_counter()
    rc = _run_nsys_profile(nsys_path, report_path, args.trace, sim_cmd)
    wallclock = time.perf_counter() - t0
    # nsys returns rc=2 for "soft" warnings (e.g. "CPU IP/backtrace sampling
    # not supported, disabling") even when the .nsys-rep archive is
    # successfully produced. We only treat the run as failed if the archive
    # is missing.
    if rc != 0 and not report_path.exists():
        return _fail(EXIT_NSYS_FAILED, f"nsys profile failed (rc={rc}, no report at {report_path})")
    if rc != 0:
        print(
            f"profile.py: nsys profile exited rc={rc} but report produced; continuing",
            file=sys.stderr,
        )

    # Post-process stats.
    try:
        csv_paths = _run_nsys_stats(nsys_path, report_path, args.out)
    except RuntimeError as exc:
        return _fail(EXIT_NSYS_FAILED, str(exc))

    summary = _summarise(csv_paths, top=args.top, wallclock_sec=wallclock)
    summary["nsys"] = nsys_path
    summary["binary"] = str(args.binary.resolve())
    summary["command"] = sim_cmd
    summary["csv_files"] = {k: str(v) for k, v in csv_paths.items()}
    (args.out / "summary.json").write_text(json.dumps(summary, indent=2))

    print(
        f"profile.py: wrote {args.out}/profile.nsys-rep "
        f"and {len(csv_paths)} CSV(s) in {wallclock:.2f}s"
    )
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
